/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminOverlay: typeof import('./components/misc/AdminOverlay.vue')['default']
    AppLayout: typeof import('./components/layouts/AppLayout.vue')['default']
    AuthorLogoBackend: typeof import('./components/misc/AuthorLogoBackend.vue')['default']
    AuthorLogoFrontend: typeof import('./components/misc/AuthorLogoFrontend.vue')['default']
    BrandSettings: typeof import('./components/shared/partners/BrandSettings.vue')['default']
    BusinessSettings: typeof import('./components/shared/partners/BusinessSettings.vue')['default']
    BuyerForm: typeof import('./components/shared/shared-forms/BuyerForm.vue')['default']
    BuyersInteractiveMap: typeof import('./components/shared/buyers/BuyersInteractiveMap.vue')['default']
    ColumnOffset: typeof import('./components/misc/ColumnOffset.vue')['default']
    ConfirmDialog: typeof import('./components/misc/ConfirmDialog.vue')['default']
    ContactForm: typeof import('./components/shared/contacts/ContactForm.vue')['default']
    ContactsTable: typeof import('./components/shared/shared-forms/ContactsTable.vue')['default']
    EditProfile: typeof import('./components/shared/settings/EditProfile.vue')['default']
    EquipmentsTable: typeof import('./components/shared/equipments/EquipmentsTable.vue')['default']
    Filler: typeof import('./components/misc/Filler.vue')['default']
    FlexedBetween: typeof import('./components/misc/FlexedBetween.vue')['default']
    InnerLayout: typeof import('./components/layouts/InnerLayout.vue')['default']
    LinkCard: typeof import('./components/shared/dashboard/LinkCard.vue')['default']
    LoginBtn: typeof import('./components/auth0/LoginBtn.vue')['default']
    LogoutBtn: typeof import('./components/auth0/LogoutBtn.vue')['default']
    MailSettings: typeof import('./components/shared/partners/MailSettings.vue')['default']
    MyModal: typeof import('./components/misc/MyModal.vue')['default']
    MyModalFrontend: typeof import('./components/misc/MyModalFrontend.vue')['default']
    NewUserModals: typeof import('./components/shared/users/NewUserModals.vue')['default']
    OffsetColumns: typeof import('./components/misc/OffsetColumns.vue')['default']
    Panel: typeof import('./components/misc/Panel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Snackbar: typeof import('./components/misc/Snackbar.vue')['default']
    Squeeze: typeof import('./components/misc/Squeeze.vue')['default']
    TableBtnIcon: typeof import('./components/misc/TableBtnIcon.vue')['default']
    TableButton: typeof import('./components/misc/TableButton.vue')['default']
    TableInput: typeof import('./components/misc/TableInput.vue')['default']
    TableItemName: typeof import('./components/misc/TableItemName.vue')['default']
    TablePrice: typeof import('./components/misc/TablePrice.vue')['default']
    TableSearch: typeof import('./components/shared/globals/TableSearch.vue')['default']
    TableSearchBox: typeof import('./components/misc/TableSearchBox.vue')['default']
    TableSelect: typeof import('./components/misc/TableSelect.vue')['default']
    TextEditor: typeof import('./components/misc/TextEditor.vue')['default']
    ThemeIcon: typeof import('./components/misc/ThemeIcon.vue')['default']
    ThemeSwitcher: typeof import('./components/misc/ThemeSwitcher.vue')['default']
    Tooltip: typeof import('./components/misc/Tooltip.vue')['default']
    UccBuyersFilters: typeof import('./components/shared/buyers/UccBuyersFilters.vue')['default']
    UccBuyerViewer: typeof import('./components/shared/buyers/UccBuyerViewer.vue')['default']
    UccFilingForm: typeof import('./components/shared/shared-forms/UccFilingForm.vue')['default']
    UccFilingsFilters: typeof import('./components/shared/ucc-filings/UccFilingsFilters.vue')['default']
    UccFilingsViewer: typeof import('./components/shared/ucc-filings/UccFilingsViewer.vue')['default']
    UccFilingsViewModal: typeof import('./components/shared/ucc-filings/UccFilingsViewModal.vue')['default']
    UccFilingTable: typeof import('./components/shared/shared-forms/UccFilingTable.vue')['default']
    UsersSettings: typeof import('./components/shared/settings/UsersSettings.vue')['default']
  }
}
