/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...notfound]': RouteRecordInfo<'/[...notfound]', '/:notfound(.*)', { notfound: ParamValue<true> }, { notfound: ParamValue<false> }>,
    '/dashboard': RouteRecordInfo<'/dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    '/it-services': RouteRecordInfo<'/it-services', '/it-services', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/paperwork/[provider_id]': RouteRecordInfo<'/paperwork/[provider_id]', '/paperwork/:provider_id', { provider_id: ParamValue<true> }, { provider_id: ParamValue<false> }>,
    '/partners': RouteRecordInfo<'/partners', '/partners', Record<never, never>, Record<never, never>>,
    '/pricing': RouteRecordInfo<'/pricing', '/pricing', Record<never, never>, Record<never, never>>,
    '/proposal/[hash]': RouteRecordInfo<'/proposal/[hash]', '/proposal/:hash', { hash: ParamValue<true> }, { hash: ParamValue<false> }>,
    '/proposals/': RouteRecordInfo<'/proposals/', '/proposals', Record<never, never>, Record<never, never>>,
    '/proposals/accepted': RouteRecordInfo<'/proposals/accepted', '/proposals/accepted', Record<never, never>, Record<never, never>>,
    '/proposals/create': RouteRecordInfo<'/proposals/create', '/proposals/create', Record<never, never>, Record<never, never>>,
    '/proposals/declined': RouteRecordInfo<'/proposals/declined', '/proposals/declined', Record<never, never>, Record<never, never>>,
    '/proposals/drafts': RouteRecordInfo<'/proposals/drafts', '/proposals/drafts', Record<never, never>, Record<never, never>>,
    '/proposals/edit/[id]': RouteRecordInfo<'/proposals/edit/[id]', '/proposals/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/providers': RouteRecordInfo<'/providers', '/providers', Record<never, never>, Record<never, never>>,
    '/settings/[settings]': RouteRecordInfo<'/settings/[settings]', '/settings/:settings', { settings: ParamValue<true> }, { settings: ParamValue<false> }>,
    '/templates/': RouteRecordInfo<'/templates/', '/templates', Record<never, never>, Record<never, never>>,
    '/templates/build': RouteRecordInfo<'/templates/build', '/templates/build', Record<never, never>, Record<never, never>>,
    '/templates/edit/[id]': RouteRecordInfo<'/templates/edit/[id]', '/templates/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/users': RouteRecordInfo<'/users', '/users', Record<never, never>, Record<never, never>>,
  }
}
